output "autonomous_database_id" {
  description = "OCID of the created Autonomous AI Database."
  value       = var.create_autonomous_database ? oci_database_autonomous_database.vectordb[0].id : null
}

output "autonomous_database_name" {
  description = "Database name to use in app configuration."
  value       = var.create_autonomous_database ? oci_database_autonomous_database.vectordb[0].db_name : null
}

output "autonomous_database_service_hint" {
  description = "Typical high service name for ORACLE_DSN after unzipping the wallet."
  value       = var.create_autonomous_database ? "${lower(oci_database_autonomous_database.vectordb[0].db_name)}_high" : null
}

output "wallet_zip_path" {
  description = "Local wallet zip generated by Terraform when wallet_output_path is set."
  value       = local.generate_wallet && trimspace(var.wallet_output_path) != "" ? local_sensitive_file.wallet_zip[0].filename : null
  sensitive   = true
}

output "wallet_zip_base64" {
  description = "Base64-encoded wallet zip content. Useful in OCI Resource Manager where local file output is not meaningful."
  value       = local.generate_wallet ? oci_database_autonomous_database_wallet.vectordb[0].content : null
  sensitive   = true
}

output "api_vm_public_ip" {
  description = "Public IP for the optional API VM."
  value       = var.enable_api_vm ? (var.create_reserved_public_ip ? oci_core_public_ip.api_reserved[0].ip_address : oci_core_instance.api[0].public_ip) : null
}

output "api_url" {
  description = "FastAPI URL if the optional VM is enabled and the app is running."
  value       = var.enable_api_vm ? "http://${var.create_reserved_public_ip ? oci_core_public_ip.api_reserved[0].ip_address : oci_core_instance.api[0].public_ip}:${var.app_port}" : "Run locally with uvicorn vector_demo.api:app --reload"
}

output "ssh_command" {
  description = "SSH command for the optional API VM."
  value       = var.enable_api_vm ? "ssh ubuntu@${var.create_reserved_public_ip ? oci_core_public_ip.api_reserved[0].ip_address : oci_core_instance.api[0].public_ip}" : null
}
