CREATE TABLE demo_pdf_chunks (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_file VARCHAR2(512) NOT NULL,
  page_number NUMBER NOT NULL,
  chunk_index NUMBER NOT NULL,
  chunk_text CLOB NOT NULL,
  embedding VECTOR(768, FLOAT32) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX demo_pdf_chunks_src_idx
  ON demo_pdf_chunks (source_file, page_number, chunk_index);

-- Optional for larger data sets. Exact search is enough for this one-PDF demo.
-- CREATE VECTOR INDEX demo_pdf_chunks_vec_idx
--   ON demo_pdf_chunks (embedding)
--   ORGANIZATION NEIGHBOR PARTITIONS
--   DISTANCE COSINE
--   WITH TARGET ACCURACY 95;
